### ISSUE TITLE
tutorial - wget call needs -O ?

### ISSUE THREAD

**Issue by mschwamb** [fraserw/trippy#1]
When I run:

Get the image this tutorial assumes you have. If wget fails then you are likely on a mac, and should just download it manually
In [3]:

```
  inputFile='Polonskaya.fits'
   if not path.isfile(inputFile):
        os.system('wget http://www.canfar.phys.uvic.ca/vospace/nodes/fraserw/Polonskaya.fits?view=data')
   else:
       print "We already have the file."
```

my mac downloads the file as Polonskaya.fits?view=data . I had to add the -O Polonskaya.fits to the wget call to work okay. Is that universal? I installed wget from homebrew

**Comment by fraserw** [comment]
Added the -O option. Good idea
