### ISSUE TITLE
requested psfStarChooser feature: auto-reject psf sources near edge of field

### ISSUE THREAD

**Issue by Mikea1985** [fraserw/trippy#16]
Issue: Sometimes SExtractor will have picked out sources that are close to the edge of the field; psfStarChooser happily displays these. However, if the sources are closer to the edge of the field than the half-width of the postage-stamp cutout box (I usually use 30, for a 61*61 pixel square), then the postage-stamp won't be the same shape as all the others. If the human operator doesn't catch this (sometimes it is hard to notice that there is 1 pixel cut off the side of the square) and doesn't reject the source, the postage-stamp won't have the expected size when it gets passed to psf.modelPSF.genLookupTable, which then crashes due to being unable to average arrays of different sizes. 

Requested feature: It would be nice if psfStarChooser\* had a feature whereby it checks the size of the postage-stamps for each source and automatically rejects any that are not the correct shape. 
- = I guess this could be worked into psf.modelPSF.genLookupTable instead, but I think it's better to have it in psfStarChooser as it then ensures that everything that uses the psf stars uses the same stars. 

I'm aware that the user could just make sure to trim their catalogue before passing it to psfStarChooser, but I figured that it's always good for software to have built-in solutions to known causes-of-failures. Especially as I think this should be fairly simple to implement. 

This is not at all major or urgent. I can probably implement this myself and set up a pull-request once I have better time to look at it (so not now :-P). This issue will serve as a reminder until then.

**Comment by fraserw** [comment]
Good point. I never ran into this because I always did that outside of
trippy. Easy fix though. Send me an image on which this happens?

**Comment by Mikea1985** [comment]
Closing this issue/request, as I included this in Pull Request #18 .
