### ISSUE TITLE
Tutorial - Add a link to make it easier for people to manually download the fits image

### ISSUE THREAD

**Issue by mschwamb** [fraserw/trippy#2]
I think that would help for those that have wget issues to be able to just click a link to get the fits image.

**Comment by fraserw** [comment]
That's not something really possible inside ipython notebook because you don't really know where the notebook is being run/stored. Unless you happen to have a trick on determining where it's cached, and where the files are saved?

**Comment by mschwamb** [comment]
Okay. since the image is on cantab in then markdown part you couldn't write 

```
  or download it [here](http://www.canfar.phys.uvic.ca/vospace/nodes/fraserw/Polonskaya.fits?view=data)
```

?

**Comment by fraserw** [comment]
The trick is not the download - that's easy. It's getting the file into the correct directory where the notebook can then have access. I think I know how to do it, but would require multiple steps by the user, and would be quite messy. Thus far, no one has complained about using wget, so I will leave it as is, me thinks. 

Stupid OSX. No wget? Probably could use curl now that I think about it... derp.

**Comment by mschwamb** [comment]
okay. then closing.
