### ISSUE TITLE
autoTrim in starChooser still not great

### ISSUE THREAD

**Issue by Mikea1985** [fraserw/trippy#21]
I put forward that autoTrim (in psfStarChooser.starChooser) is still not identifying stars reliably: 
![point_source_selector](https://user-images.githubusercontent.com/14901128/40609153-63fde490-62a0-11e8-90ff-baefcdc74ba0.png)

**Comment by Mikea1985** [comment]
My latest experience with autoTrim is vastly superior to all prior experiences. From V1.0 it seems actually useful. :-) I have yet to see it do anything terrible; at most it has marked a few stars (out of several dozen) as ignored where I think "what's wrong with those?"

**Comment by fraserw** [comment]
That's fantastic. Really glad my efforts weren't in vain! ha

Next on the list is to include the clustering I was talking about.
Specifically, I have found if one clusters on the 4D space of FWHM, A, B,
and Kron-aperture magnitude, then stars are clustered very cleanly in the
cluster that has the smallest mean FWHM, if one starts with SNR>~150
sources. This only really works when one has a moderate to large FOV, or
a dense field. But it works beautifully over 10 TB worth of HSC data! :)

**Comment by Mikea1985** [comment]
One method for identifying stars that I learnt about from somewhere one the Pan-STARRS catalog website (or somewhere else talking about it) is to compare the Kron and small aperture photometry: for stars the two methods should result in very similar mags, while for galaxies the small aperture underestimates the total flux. Maybe that can be useful here too? I know SExtractor does several kinds of photometry.

**Comment by fraserw** [comment]
That's one of the parameters I cluster on. Does very well for all but
spheroidal galaxies, which the others can trim out.
