### ISSUE TITLE
Things look different in matplotlib version 2.x

### ISSUE THREAD

**Issue by Mikea1985** [fraserw/trippy#22]
Having installed the newest ``matplotlib`` in my new anaconda environment and on my students computer, I realise that there are a bunch of visual changes between ``matplotlib`` 1.x and 2.x. We need to assess whether any of these mean that we need to edit ``trippy``. 

For example, here is the ``psfStarChooser.starChooser`` generated using ``matplotlib`` 1.5.1:
![point_source_selector-mpl1](https://user-images.githubusercontent.com/14901128/41133927-4f53d4f0-6afc-11e8-8b6b-f4183f94d8b9.png)
and using ``matplotlib`` 2.2.2:
![point_source_selector-mpl2](https://user-images.githubusercontent.com/14901128/41133936-55a7147a-6afc-11e8-8d57-601157a4fd3d.png)

All of the visual changes to ``matplotlib`` between 1.x and 2.x are explained/listed here: https://matplotlib.org/users/dflt_style_changes.html including a video explaining the choice of the new default colour map. 

At least for the ``starChooser``, I think it still looks fine, and probably doesn't require any changes, but I haven't checked any of the other figures that ``trippy`` can produce yet.

**Comment by Mikea1985** [comment]
The figure produced by ``pill.pillPhot`` look fine too. 
1.5.1:
![phot_display_1 5 1](https://user-images.githubusercontent.com/14901128/41135928-61d81a82-6b06-11e8-9785-ae4a0ae181e0.png)
2.2.2:
![phot_display_2 2 2](https://user-images.githubusercontent.com/14901128/41135937-67fcdfba-6b06-11e8-97f6-4615a8c3efdc.png)

I'm not sure what I think about the new colour map, though. It makes if far harder to see variations in the background, and which is important in cases where you want to trim some of the background off, like near a star or the edge of the field for images that have a mean-background padding around the edge, like Gemini images do, see examples below. 
1.5.1: Here I can easily see that part of the background being shown is in fact non-read padding that has been added to the image. It is easy to trim off that part: **
![image_display-1](https://user-images.githubusercontent.com/14901128/41137133-183905de-6b0c-11e8-9ad9-79382b1bb031.png)
2.2.2: Here I can't see what part of the background is the offending part. It's obvious from the histogram what is going on, but the image shown does not have the contrast to let me see how to fix it:
![image_display-2](https://user-images.githubusercontent.com/14901128/41137204-7ed1ea68-6b0c-11e8-9629-d618a63ee5f8.png)
The solution here might just be to tweak how the ``normer`` that is used for the plot gets defined. I can look at that later, probably.  

**(yes yes, this source obviously shouldn't be used for multiple reasons (probably a galaxy and it clearly has a bad pixel problem), but I'm just demonstrating a point)

**Comment by fraserw** [comment]
Checking in here too. Is this still an issue for you? If so, I'll look into a better colour map.
