### ISSUE TITLE
problem with starChooser

### ISSUE THREAD

**Issue by aserebryanskiy** [fraserw/trippy#28]
When I tried to follow the instruction in the tutorial I've stumbled on an error in starChooser:
------------
 File "/home/alex/anaconda2/envs/iraf27/lib/python2.7/site-packages/trippy/psf.py", line 719, in fitMoffat
    lsqf = opti.leastsq(self._resid,(peakGuess,self.alpha,self.beta),args=(fitMaxRadius),maxfev=250)

  File "/home/alex/.local/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 394, in leastsq
    gtol, maxfev, epsfcn, factor, diag)
"ValueError: The array returned by a function changed size between calls"
-----------
what may cause this problem? Or the instruction is out of date?

**Comment by Mikea1985** [comment]
This is a known problem, that I was actually just coming here to open an issue about. It’s because in the old scipy, passing np.inf when parameters went to unphysical ranges was acceptable. With scipy 1+ one has to pass an array of infs.

A quick fix solution is to downgrade your scipy version to the latest version known to work with Trippy, scipy version 0.17.1
However, long-term, this should get fixed in trippy.psf 
Some day I'll get to it.

**Comment by aserebryanskiy** [comment]
Thanks for the helpful reply! 

===========================Aleksander Serebryanskiy, PhDFesenkov Astrophysical Institute,Observatory 23, 050020 Almaty, Kazakhstan 
tel: 8(747)9393892e-mail: alex@aphi.kz, aserebryanskiy@yahoo.com 

    On Monday, January 28, 2019, 8:40:44 AM GMT+6, Mike Alexandersen <notifications@github.com> wrote:  
 
 
This is a known problem, that I was actually just coming here to open an issue about. It’s because in the old scipy, passing np.inf when parameters went to unphysical ranges was acceptable. With scipy 1+ one has to pass an array of infs.

A quick fix solution is to downgrade your scipy version to the latest version known to work with Trippy, scipy version 0.17.1
However, long-term, this should get fixed in trippy.psf
Some day I'll get to it.

**Comment by Mikea1985** [comment]
I believe this issue was fixed in the version 1.0 release.

**Comment by aserebryanskiy** [comment]
Dear Mike,
Thanks for notifying me about that! I'll return back to asteroid trail analysis soon and will let you know about my progress.I believe trippy can be used for star-trails photometry and astrometry too. 
Alex
===========================Aleksander Serebryanskiy, PhDFesenkov Astrophysical Institute,Observatory 23, 050020 Almaty, Kazakhstan 
tel: 8(747)9393892e-mail: alex@aphi.kz, aserebryanskiy@yahoo.com 

    On Wednesday, August 7, 2019, 07:20:03 AM GMT+6, Mike Alexandersen <notifications@github.com> wrote:  
 
 
I believe this issue was fixed in the version 1.0 release.

**Comment by fraserw** [comment]
Hi all

Alex, it certainly can be. I used it for photometry of Oumuamua which was
stationary in our images, and the background stars which were exceptionally
elongated.

Don't hesitate to reach out for assistance on anything trippy!

Wes

**Comment by aserebryanskiy** [comment]
Hi Wess,
It's super interesting and important for our work too. We have several options for data reduction but it's always wise to have as many tools as possible and your trippy seems to be a very appropriate one. I guess we may try to use it for geostationary satellite analysis, etc.  
Thanks for providing kind assistance with trippy!
Alex
===========================Aleksander Serebryanskiy, PhDFesenkov Astrophysical Institute,Observatory 23, 050020 Almaty, Kazakhstan 
tel: 8(747)9393892e-mail: alex@aphi.kz, aserebryanskiy@yahoo.com 

    On Wednesday, August 7, 2019, 10:25:36 AM GMT+6, Wesley Fraser <notifications@github.com> wrote:  
 
 Hi all

Alex, it certainly can be. I used it for photometry of Oumuamua which was
stationary in our images, and the background stars which were exceptionally
elongated.

Don't hesitate to reach out for assistance on anything trippy!

Wes
