### ISSUE TITLE
Provide sextractor param files used in the tutorial

### ISSUE THREAD

**Issue by mschwamb** [fraserw/trippy#3]
It would be nice to know what parameters from sextractor are being used by trippy. To get the tutorial to run, I had to download the default files and it seemed to work okay, but I don't know if what was needed was actually in there or what magnitude/flux measurement from sextractor is being used to make selections for the psf

**Comment by fraserw** [comment]
I don't understand what you are saying. The sextractor files are created by the makeParFiles commands.  That is not stated explicitly. So I can fix that. 

As for what parameters are being used, I thought that was obvious from the code, where it has lines like "XWIN_IMAGE"... but I can also make that more clear in the markdown.

If that's not what you were looking for, mind clarifying?

**Comment by mschwamb** [comment]
Yeah that solves it. I just missed that when ready the text. Making it more clear in the markdown would be helpful.
