### ISSUE TITLE
Reuse "saved" background, or similar

### ISSUE THREAD

**Issue by Mikea1985** [fraserw/trippy#34]
I just had a conversation with Rosemary, and wanted to write down the gist of it, more as a reminder for future development than as an immediate issue requiring attention. 

Basically, it boils down "make life easier for when you have to re-process your data several times", which of course means removing any steps where a human has to interfere/click on something.  Currently a PSF model can be loaded from a saved file, which allows the user to skip the biggest human-interactionstep (the psfStarChooser step) during reprocessing (assuming PSF model is trusted). However, unless one is happy with either the full background box or the automatic trimming (using ``trimBGHighPix``), there is no way to skip the background inspection/selection step of the ``pill.pillPhot`` call. 

We proposed two solutions (requiring different ammounts of effort to implement): 
- Implement a keyword (eg. ``displayIfHighPix``) such that if ``display=False`` and ``displayIfHighPix=True``, you do not see the background selection window unless there are pixels that meet the ``timBGHighPix`` threshold. 
- Implement some way to save the used background parameters to a file, so that the next time the script is run, it checks whether the background has already been measured. The information saved should be: (X,Y) coordinate of the object in question, 4 coordinates of the corners of the selected background rectangle, and the calculated background value. On re-processing, the script would then check whether the target that you are currently trying to measure photometry for already has background information in the background-info file and uses that if available. Whether or not to save, and whether or not to load from the saved file, could of course be toggled on or off with keywords. 

One or both of these would make it a lot faster to quickly re-process data automatically in-full without any human intervention.

**Comment by fraserw** [comment]
Both of these things are essentially already implemented.

option one can be had with display=False and enableBGselection=False. Trimming high pixels can occur with or without the display.

The second option is the zoomRegion option. This has been documented in the pillPhot.__call__ function for a while, but not shown in the tutorial for clarity. So it isn't surprising you missed it. if zoomRegion is provided a float 4-tuple, it will automatically set to that region. **display=True and enableBGselection = True** for this to work.  

Accessing the selected region once photometry has been done is though the pillPhot.beSelectionRegion variable. This was accidentally ommitted from the function documentation. 

I have updated the function call doc string to inform the bgSelectionRegion bit.
