### ISSUE TITLE
Invalid value - runtime warning in python 3 and numpy==1.17.0

### ISSUE THREAD

**Issue by mschwamb** [fraserw/trippy#38]
Computing aperture corrections of each good star...
/Users/mschwamb/anaconda3/lib/python3.7/site-packages/trippy/trippy_utils.py:84: RuntimeWarning: invalid value encountered in double_scalars
  self.m = (p2[1]-p1[1])/(p2[0]-p1[0])
/Users/mschwamb/anaconda3/lib/python3.7/site-packages/trippy/trippy_utils.py:84: RuntimeWarning: divide by zero encountered in double_scalars
  self.m = (p2[1]-p1[1])/(p2[0]-p1[0])

**Comment by mschwamb** [comment]
this might be me sending Nans so closing for now

**Comment by fraserw** [comment]
Yup. Not actually an issue. Never found a way to deal with this that didn’t also come along with a large speed penalty. So just letting numpy handle it.
