### ISSUE TITLE
what does dmagnitude =（2.5/log(10)）*  (1/SNR) mean?

### ISSUE THREAD

**Issue by SophicSansan** [fraserw/trippy#40]

**Comment by fraserw** [comment]
This is an estimate of the uncertainty of the magnitude measurement, based simply from the signal-to-noise of the measurement. The equation is derived from the magnitude equation: m=2.5*log(flux).

**Comment by fraserw** [comment]
Marking this issue as closed, as it really isn't an issue with the software.

**Comment by SophicSansan** [comment]
Thank you very much!!

**Comment by SophicSansan** [comment]
> 



> This is an estimate of the uncertainty of the magnitude measurement, based simply from the signal-to-noise of the measurement. The equation is derived from the magnitude equation: m=2.5*log(flux).

Thank you very much!!
