### ISSUE TITLE
Adding in annimated gif of selected stars for psf generation

### ISSUE THREAD

**Issue by mschwamb** [fraserw/trippy#5]
I was a little not sure which window and what happens when I do the selection on the window size, so I made an animated gif if something like this would be helpful for the ipython guide 

![trippy](https://cloud.githubusercontent.com/assets/753325/12344438/f83f6e80-bb77-11e5-9119-66a3f3b597e4.gif)

**Comment by fraserw** [comment]
Like the pdf, no way to do that. Lots of people have used this tool at this point with no issue, so I don't really think it all that necessary. Use it once following along the tutorial, never have to think about it again. Or at least, so everyone's experience has gone.
