### ISSUE TITLE
AttributeError: pillPhot instance has no attribute 'l1'

### ISSUE THREAD

**Issue by mschwamb** [fraserw/trippy#6]
Going through the tutorial I'm getting this error:

Traceback (most recent call last):
  File "testrippy.py", line 112, in <module>
    mode="smart",trimBGHighPix=3.)
  File "/Users/mschwamb/anaconda/lib/python2.7/site-packages/trippy/pill.py", line 149, in **call**
    l1=self.l1
AttributeError: pillPhot instance has no attribute 'l1'

I did a trippy pip install update and the error still occurs

The steps I'm taking are in [this python file](https://www.dropbox.com/s/y4hj3m4auvvjbt5/testrippy.py?dl=0) 

I did a trippy

**Comment by fraserw** [comment]
That should not exist if you are on the most recent trippy. Can you get me a version number?

**Comment by mschwamb** [comment]
i don't know since when I wrote out for the version that doesn't work. I've been using pip install trippy --upgrade so In thought that she be enough, but somehow doing it again has screwed up my anaconda install and I had to reinstall all of that. After that it seems fine.

Could there be an issue with the pip install --upgrade?

Now after removing everything I get it to give me the same results without the error.

**Comment by fraserw** [comment]
Can you provide all of the steps you do to get to this error? You're the only one getting it, and it was a bug in an older version, so I am surprised to see it.

**Comment by mschwamb** [comment]
The steps I'm taking are in [this python file](https://www.dropbox.com/s/y4hj3m4auvvjbt5/testrippy.py?dl=0) 

I uninstalled trippy with pip uninstall trippy because I had the test server version.

So since I assumed the dependencies were still installed I did a pip install trippy.

Then it gave me that weird result after I did a trippy install trippy --upgrade

Doing that again, broke my matplotlib. So I did a complete fresh install of anaconda, and then when through your installation instructions step by step again

**Comment by fraserw** [comment]
I have no idea what's wrong. Can you do a print trippy.**version** please?

**Comment by fraserw** [comment]
And that was supposed to be double underscore version double underscore. Markdown is changing it.

**Comment by mschwamb** [comment]
Doing the complete fresh install of anaconda and then full reinstall seems to have fixed it and I don't get this error. I don't get why doing an upgrade what caused any issues

0.2.5 is the version I have running now

**Comment by mschwamb** [comment]
resolved
